// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjPdsMYtfbrp36MZYeKiNcXjGIrbUO4O0',
    appId: '1:613119900476:web:87e7d5d86d031b6ec6bc39',
    messagingSenderId: '613119900476',
    projectId: 'busway-33f45',
    authDomain: 'busway-33f45.firebaseapp.com',
    storageBucket: 'busway-33f45.appspot.com',
    measurementId: 'G-LQ8W23Q0VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSd9PHaaABoLma_txNu0NMgJuArFixtTM',
    appId: '1:613119900476:android:5d247e54f6f60c70c6bc39',
    messagingSenderId: '613119900476',
    projectId: 'busway-33f45',
    storageBucket: 'busway-33f45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_skG5EERHpgD3eZe68UjV2wk3MFg4RgE',
    appId: '1:613119900476:ios:3e7eba4ec9a8c3eac6bc39',
    messagingSenderId: '613119900476',
    projectId: 'busway-33f45',
    storageBucket: 'busway-33f45.appspot.com',
    iosBundleId: 'com.example.busFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_skG5EERHpgD3eZe68UjV2wk3MFg4RgE',
    appId: '1:613119900476:ios:3bbcdfe4cfe640f2c6bc39',
    messagingSenderId: '613119900476',
    projectId: 'busway-33f45',
    storageBucket: 'busway-33f45.appspot.com',
    iosBundleId: 'com.example.busFinder.RunnerTests',
  );
}
